server:
  port: ${PORT:8080}
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: yoga-business-management-web
  data:
    mongodb:
      uri: mongodb+srv://yoga:8bpSXd1qKwBM1RJ0@yoga.v47pt.mongodb.net/?retryWrites=true&w=majority&appName=Yoga
      database: yoga

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${PORT:8080}
    title: API Service
    version: 1.0.0

jwt:
  expiryTime: ${JWT_EXPIRY_TIME}
  secretKey: ${JWT_SECRET_KEY}
  refreshkey: ${JWT_REFRESH_KEY}
  resetKey: ${JWT_RESET_KEY}
